### ISSUE TITLE
Оформление репозитория

### ISSUE THREAD

**Issue by tshemsedinov** [La7rodectus/Aim_trainer#1]
- [x] Добавить eslint и конфигурацию, лучше взять эту: [.eslintrc.json](https://github.com/HowProgrammingWorks/NodejsStarterKit/blob/master/.eslintrc.json)
- [x] Добавить `README.md` 1-2 страницы описания проекта и кода
- [x] Добавить лицензию, например MIT
- [x] Добавить `package.json` с зависимостями, тем же eslint. Пример: [package.json](https://github.com/HowProgrammingWorks/NodejsStarterKit/blob/master/package.json)

**Comment by La7rodectus** [comment]
Підправив.
